#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running pre-commit fixes..."

# Run lint-staged for all staged files
bun lint-staged

# Run format and lint for all packages
bun run format
bun run lint 